CREATE TABLE CUSTOMER (
CUSTOMER_ID   INT IDENTITY PRIMARY KEY,  -- 顧客ID
CUSTOMER_NAME VARCHAR(50) NOT NULL,      -- 顧客名
PASSWORD      VARCHAR(60) NOT NULL,      -- パスワード
EMAIL         VARCHAR(200) NOT NULL,     -- Eメールアドレス
BIRTHDAY      DATE,                      -- 生年月日
ADDRESS       VARCHAR(120),              -- 住所（UTF-8で40文字）
CONSTRAINT EMAIL_UNIQUE UNIQUE(EMAIL)
);