openapi: 3.0.3
info:
  title: Books Stock API - カテゴリAPI
  description: |
    バックオフィス書籍在庫管理システムのカテゴリAPI仕様
    
    書籍カテゴリマスタ情報の参照機能を提供する。
  version: 1.0.0
  contact:
    name: API Support
    email: support@example.com

servers:
  - url: http://localhost:8080/api
    description: 開発環境
  - url: https://api.example.com/api
    description: 本番環境

tags:
  - name: categories
    description: カテゴリ操作

paths:
  /categories:
    get:
      tags:
        - categories
      summary: カテゴリ一覧取得
      description: すべてのカテゴリ情報を配列形式で取得する
      operationId: getAllCategories
      responses:
        '200':
          description: カテゴリ一覧取得成功
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
        '500':
          description: サーバー内部エラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    Category:
      type: object
      properties:
        categoryId:
          type: integer
          format: int32
          description: カテゴリID
          example: 1
        categoryName:
          type: string
          description: カテゴリ名
          example: 文学

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: エラータイプ
          example: InternalServerError
        message:
          type: string
          description: エラーメッセージ（日本語）
          example: サーバー内部エラーが発生しました
