-- ============================================
-- Berry Books API: テーブル定義
-- ============================================
-- 注文テーブルのみ（書籍・在庫はback-office-api、顧客はcustomer-hub-api）

CREATE TABLE ORDER_TRAN (
ORDER_TRAN_ID    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 注文取引ID
ORDER_DATE       DATE NOT NULL,                                         -- 注文日
CUSTOMER_ID      INT NOT NULL,                                          -- 顧客ID（論理的参照のみ）
TOTAL_PRICE      INT NOT NULL,                                          -- 注文金額合計
DELIVERY_PRICE   INT NOT NULL,                                          -- 配送料金
DELIVERY_ADDRESS VARCHAR(30) NOT NULL,                                  -- 配送先住所
SETTLEMENT_TYPE  INT NOT NULL                                           -- 決済方法
-- 注意: CUSTOMER_IDへの外部キー制約なし（customer-hub-apiに分離）
);

CREATE TABLE ORDER_DETAIL (
ORDER_TRAN_ID   INT NOT NULL,                                          -- 注文取引ID
ORDER_DETAIL_ID INT NOT NULL,                                          -- 注文明細ID
BOOK_ID         INT NOT NULL,                                          -- 書籍ID（論理的参照のみ）
BOOK_NAME       VARCHAR(80) NOT NULL,                                  -- 書籍名（スナップショット：注文時点の名称を保持）
PUBLISHER_NAME  VARCHAR(80),                                           -- 出版社名（スナップショット：注文時点の名称を保持）
PRICE           INT NOT NULL,                                          -- 価格（スナップショット：注文時点の価格を保持）
COUNT           INT NOT NULL,                                          -- 注文数
CONSTRAINT PK_ORDER_DETAIL
    PRIMARY KEY(ORDER_TRAN_ID, ORDER_DETAIL_ID),
CONSTRAINT FK_ORDER_TRAN_ID FOREIGN KEY(ORDER_TRAN_ID)
    REFERENCES ORDER_TRAN(ORDER_TRAN_ID)
-- 設計方針:
--   - BOOK_IDへの外部キー制約なし（back-office-apiに書籍マスタが分離されているため）
--   - BOOK_NAME/PUBLISHER_NAME/PRICEは意図的に非正規化（注文時点のスナップショットを保持）
--   - 理由1: 書籍マスタが変更されても過去の注文履歴は変わらない
--   - 理由2: 書籍が削除されても注文履歴を表示可能
--   - 理由3: 注文履歴表示時に外部API呼び出し不要（パフォーマンス向上）
);
