-- Berry Books API サンプルデータ

-- 出版社
INSERT INTO PUBLISHER (PUBLISHER_NAME) VALUES ('技術評論社');
INSERT INTO PUBLISHER (PUBLISHER_NAME) VALUES ('オライリー・ジャパン');
INSERT INTO PUBLISHER (PUBLISHER_NAME) VALUES ('翔泳社');
INSERT INTO PUBLISHER (PUBLISHER_NAME) VALUES ('日経BP');

-- カテゴリ
INSERT INTO CATEGORY (CATEGORY_NAME) VALUES ('プログラミング');
INSERT INTO CATEGORY (CATEGORY_NAME) VALUES ('データベース');
INSERT INTO CATEGORY (CATEGORY_NAME) VALUES ('ネットワーク');
INSERT INTO CATEGORY (CATEGORY_NAME) VALUES ('AI・機械学習');

-- 書籍
INSERT INTO BOOK (BOOK_NAME, AUTHOR, CATEGORY_ID, PUBLISHER_ID, PRICE) 
VALUES ('Java完全理解', '山田太郎', 1, 1, 3200);

INSERT INTO BOOK (BOOK_NAME, AUTHOR, CATEGORY_ID, PUBLISHER_ID, PRICE) 
VALUES ('データベース設計入門', '佐藤花子', 2, 2, 2800);

INSERT INTO BOOK (BOOK_NAME, AUTHOR, CATEGORY_ID, PUBLISHER_ID, PRICE) 
VALUES ('ネットワーク基礎', '鈴木一郎', 3, 3, 3000);

INSERT INTO BOOK (BOOK_NAME, AUTHOR, CATEGORY_ID, PUBLISHER_ID, PRICE) 
VALUES ('機械学習実践ガイド', '田中次郎', 4, 4, 3800);

INSERT INTO BOOK (BOOK_NAME, AUTHOR, CATEGORY_ID, PUBLISHER_ID, PRICE) 
VALUES ('Pythonプログラミング', '伊藤美咲', 1, 1, 2900);

-- 在庫
INSERT INTO STOCK (BOOK_ID, QUANTITY, VERSION) VALUES (1, 10, 0);
INSERT INTO STOCK (BOOK_ID, QUANTITY, VERSION) VALUES (2, 5, 0);
INSERT INTO STOCK (BOOK_ID, QUANTITY, VERSION) VALUES (3, 8, 0);
INSERT INTO STOCK (BOOK_ID, QUANTITY, VERSION) VALUES (4, 3, 0);
INSERT INTO STOCK (BOOK_ID, QUANTITY, VERSION) VALUES (5, 15, 0);

-- 顧客（パスワードはBCryptハッシュまたは平文）
INSERT INTO CUSTOMER (CUSTOMER_NAME, PASSWORD, EMAIL, BIRTHDAY, ADDRESS)
VALUES ('Alice', 'password', 'alice@gmail.com', '1990-01-01', '東京都渋谷区神南1-1-1');

INSERT INTO CUSTOMER (CUSTOMER_NAME, PASSWORD, EMAIL, BIRTHDAY, ADDRESS)
VALUES ('Bob', 'password', 'bob@gmail.com', '1985-05-15', '大阪府大阪市北区梅田1-1-1');

INSERT INTO CUSTOMER (CUSTOMER_NAME, PASSWORD, EMAIL, BIRTHDAY, ADDRESS)
VALUES ('Charlie', 'password', 'charlie@gmail.com', '1992-12-25', '沖縄県那覇市おもろまち1-1-1');

