package pro.kensait.jsf.person.service;

import java.util.List;
import jakarta.enterprise.context.RequestScoped;
import jakarta.persistence.EntityManager;
import jakarta.persistence.PersistenceContext;
import jakarta.transaction.Transactional;
import pro.kensait.jsf.person.entity.Person;

/**
 * PersonService class provides business logic for Person entity operations.
 * This service handles all CRUD operations for Person entities with transactional support.
 */
@RequestScoped
@Transactional
public class PersonService {

    /**
     * EntityManager injected by container
     */
    @PersistenceContext(unitName = "personPU")
    private EntityManager em;

    /**
     * Retrieve all Person records from the database.
     * Results are ordered by personId in ascending order.
     * 
     * @return List of all Person entities
     */
    public List<Person> getAllPersons() {
        return em.createQuery("SELECT p FROM Person p ORDER BY p.personId", Person.class)
                .getResultList();
    }

    /**
     * Retrieve a Person by their ID.
     * 
     * @param personId The ID of the person to retrieve
     * @return The Person entity if found, null otherwise
     */
    public Person getPersonById(Integer personId) {
        return em.find(Person.class, personId);
    }

    /**
     * Add a new Person to the database.
     * The personId will be automatically generated by the database.
     * 
     * @param person The Person entity to add (personId should be null for new records)
     */
    public void addPerson(Person person) {
        em.persist(person);
    }

    /**
     * Update an existing Person in the database.
     * 
     * @param person The Person entity to update (must have a valid personId)
     */
    public void updatePerson(Person person) {
        em.merge(person);
    }

    /**
     * Delete a Person from the database by their ID.
     * 
     * @param personId The ID of the person to delete
     * @throws RuntimeException if the person with the specified ID is not found
     */
    public void deletePerson(Integer personId) {
        Person person = em.find(Person.class, personId);
        if (person == null) {
            throw new RuntimeException("Person with ID " + personId + " not found");
        }
        em.remove(person);
    }
}
