-- ============================================================================
-- berry-books DDL Script for HSQLDB
-- ============================================================================
-- プロジェクトID: berry-books
-- バージョン: 1.0.0
-- 最終更新日: 2025-12-20
-- 対象データベース: HSQLDB 2.7.x
-- ============================================================================

-- ============================================================================
-- テーブルの削除（既存データクリーンアップ）
-- ============================================================================
DROP TABLE IF EXISTS ORDER_DETAIL;
DROP TABLE IF EXISTS ORDER_TRAN;
DROP TABLE IF EXISTS CUSTOMER;
DROP TABLE IF EXISTS STOCK;
DROP TABLE IF EXISTS BOOK;
DROP TABLE IF EXISTS CATEGORY;
DROP TABLE IF EXISTS PUBLISHER;

-- ============================================================================
-- 1. PUBLISHER (出版社マスタ)
-- ============================================================================
CREATE TABLE PUBLISHER (
    PUBLISHER_ID    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PUBLISHER_NAME  VARCHAR(30) NOT NULL
);

COMMENT ON TABLE PUBLISHER IS '出版社マスタ';
COMMENT ON COLUMN PUBLISHER.PUBLISHER_ID IS '出版社ID（自動採番）';
COMMENT ON COLUMN PUBLISHER.PUBLISHER_NAME IS '出版社名';

-- ============================================================================
-- 2. CATEGORY (カテゴリマスタ)
-- ============================================================================
CREATE TABLE CATEGORY (
    CATEGORY_ID     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CATEGORY_NAME   VARCHAR(20) NOT NULL
);

COMMENT ON TABLE CATEGORY IS 'カテゴリマスタ';
COMMENT ON COLUMN CATEGORY.CATEGORY_ID IS 'カテゴリID（自動採番）';
COMMENT ON COLUMN CATEGORY.CATEGORY_NAME IS 'カテゴリ名';

-- ============================================================================
-- 3. BOOK (書籍)
-- ============================================================================
CREATE TABLE BOOK (
    BOOK_ID         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    BOOK_NAME       VARCHAR(80) NOT NULL,
    AUTHOR          VARCHAR(40) NOT NULL,
    CATEGORY_ID     INTEGER NOT NULL,
    PUBLISHER_ID    INTEGER NOT NULL,
    PRICE           INTEGER NOT NULL,
    CONSTRAINT FK_BOOK_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID),
    CONSTRAINT FK_BOOK_PUBLISHER FOREIGN KEY (PUBLISHER_ID) REFERENCES PUBLISHER(PUBLISHER_ID),
    CONSTRAINT CHK_BOOK_PRICE CHECK (PRICE >= 0)
);

COMMENT ON TABLE BOOK IS '書籍マスタ';
COMMENT ON COLUMN BOOK.BOOK_ID IS '書籍ID（自動採番）';
COMMENT ON COLUMN BOOK.BOOK_NAME IS '書籍名';
COMMENT ON COLUMN BOOK.AUTHOR IS '著者名';
COMMENT ON COLUMN BOOK.CATEGORY_ID IS 'カテゴリID（外部キー）';
COMMENT ON COLUMN BOOK.PUBLISHER_ID IS '出版社ID（外部キー）';
COMMENT ON COLUMN BOOK.PRICE IS '価格（円）';

-- インデックス作成（検索最適化）
CREATE INDEX IDX_BOOK_CATEGORY ON BOOK(CATEGORY_ID);
CREATE INDEX IDX_BOOK_NAME ON BOOK(BOOK_NAME);

-- ============================================================================
-- 4. STOCK (在庫)
-- ============================================================================
CREATE TABLE STOCK (
    BOOK_ID         INTEGER PRIMARY KEY,
    QUANTITY        INTEGER NOT NULL,
    VERSION         BIGINT NOT NULL,
    CONSTRAINT FK_STOCK_BOOK FOREIGN KEY (BOOK_ID) REFERENCES BOOK(BOOK_ID),
    CONSTRAINT CHK_STOCK_QUANTITY CHECK (QUANTITY >= 0)
);

COMMENT ON TABLE STOCK IS '在庫マスタ（楽観的ロック対応）';
COMMENT ON COLUMN STOCK.BOOK_ID IS '書籍ID（外部キー）';
COMMENT ON COLUMN STOCK.QUANTITY IS '在庫数';
COMMENT ON COLUMN STOCK.VERSION IS 'バージョン番号（楽観的ロック用）';

-- ============================================================================
-- 5. CUSTOMER (顧客)
-- ============================================================================
CREATE TABLE CUSTOMER (
    CUSTOMER_ID     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CUSTOMER_NAME   VARCHAR(30) NOT NULL,
    EMAIL           VARCHAR(30) NOT NULL,
    PASSWORD        VARCHAR(60) NOT NULL,
    BIRTHDAY        DATE,
    ADDRESS         VARCHAR(120),
    CONSTRAINT UK_CUSTOMER_EMAIL UNIQUE (EMAIL)
);

COMMENT ON TABLE CUSTOMER IS '顧客マスタ';
COMMENT ON COLUMN CUSTOMER.CUSTOMER_ID IS '顧客ID（自動採番）';
COMMENT ON COLUMN CUSTOMER.CUSTOMER_NAME IS '顧客名';
COMMENT ON COLUMN CUSTOMER.EMAIL IS 'メールアドレス（一意）';
COMMENT ON COLUMN CUSTOMER.PASSWORD IS 'パスワード（平文、学習用のみ）';
COMMENT ON COLUMN CUSTOMER.BIRTHDAY IS '生年月日';
COMMENT ON COLUMN CUSTOMER.ADDRESS IS '住所';

-- インデックス作成（ログイン最適化）
CREATE UNIQUE INDEX IDX_CUSTOMER_EMAIL ON CUSTOMER(EMAIL);

-- ============================================================================
-- 6. ORDER_TRAN (注文取引)
-- ============================================================================
CREATE TABLE ORDER_TRAN (
    ORDER_TRAN_ID       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ORDER_DATE          TIMESTAMP NOT NULL,
    CUSTOMER_ID         INTEGER NOT NULL,
    TOTAL_PRICE         INTEGER NOT NULL,
    DELIVERY_PRICE      INTEGER NOT NULL,
    DELIVERY_ADDRESS    VARCHAR(30) NOT NULL,
    SETTLEMENT_TYPE     INTEGER NOT NULL,
    CONSTRAINT FK_ORDER_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
    CONSTRAINT CHK_ORDER_TOTAL_PRICE CHECK (TOTAL_PRICE >= 0),
    CONSTRAINT CHK_ORDER_DELIVERY_PRICE CHECK (DELIVERY_PRICE >= 0),
    CONSTRAINT CHK_ORDER_SETTLEMENT CHECK (SETTLEMENT_TYPE IN (1, 2, 3))
);

COMMENT ON TABLE ORDER_TRAN IS '注文取引';
COMMENT ON COLUMN ORDER_TRAN.ORDER_TRAN_ID IS '注文取引ID（自動採番）';
COMMENT ON COLUMN ORDER_TRAN.ORDER_DATE IS '注文日時';
COMMENT ON COLUMN ORDER_TRAN.CUSTOMER_ID IS '顧客ID（外部キー）';
COMMENT ON COLUMN ORDER_TRAN.TOTAL_PRICE IS '注文金額合計（円）';
COMMENT ON COLUMN ORDER_TRAN.DELIVERY_PRICE IS '配送料金（円）';
COMMENT ON COLUMN ORDER_TRAN.DELIVERY_ADDRESS IS '配送先住所';
COMMENT ON COLUMN ORDER_TRAN.SETTLEMENT_TYPE IS '決済方法（1:銀行振込, 2:クレジット, 3:着払い）';

-- インデックス作成（注文履歴クエリ用）
CREATE INDEX IDX_ORDER_CUSTOMER ON ORDER_TRAN(CUSTOMER_ID);
CREATE INDEX IDX_ORDER_DATE ON ORDER_TRAN(ORDER_DATE);

-- ============================================================================
-- 7. ORDER_DETAIL (注文明細)
-- ============================================================================
CREATE TABLE ORDER_DETAIL (
    ORDER_TRAN_ID       INTEGER NOT NULL,
    ORDER_DETAIL_ID     INTEGER NOT NULL,
    BOOK_ID             INTEGER NOT NULL,
    PRICE               INTEGER NOT NULL,
    COUNT               INTEGER NOT NULL,
    CONSTRAINT PK_ORDER_DETAIL PRIMARY KEY (ORDER_TRAN_ID, ORDER_DETAIL_ID),
    CONSTRAINT FK_ORDER_DETAIL_TRAN FOREIGN KEY (ORDER_TRAN_ID) REFERENCES ORDER_TRAN(ORDER_TRAN_ID),
    CONSTRAINT FK_ORDER_DETAIL_BOOK FOREIGN KEY (BOOK_ID) REFERENCES BOOK(BOOK_ID),
    CONSTRAINT CHK_ORDER_DETAIL_PRICE CHECK (PRICE >= 0),
    CONSTRAINT CHK_ORDER_DETAIL_COUNT CHECK (COUNT >= 1)
);

COMMENT ON TABLE ORDER_DETAIL IS '注文明細';
COMMENT ON COLUMN ORDER_DETAIL.ORDER_TRAN_ID IS '注文取引ID（外部キー）';
COMMENT ON COLUMN ORDER_DETAIL.ORDER_DETAIL_ID IS '注文明細ID（注文内連番）';
COMMENT ON COLUMN ORDER_DETAIL.BOOK_ID IS '書籍ID（外部キー）';
COMMENT ON COLUMN ORDER_DETAIL.PRICE IS '価格（注文時点の書籍価格）';
COMMENT ON COLUMN ORDER_DETAIL.COUNT IS '注文数';

-- インデックス作成（書籍販売分析用）
CREATE INDEX IDX_ORDER_DETAIL_BOOK ON ORDER_DETAIL(BOOK_ID);

-- ============================================================================
-- DDLスクリプト完了
-- ============================================================================
-- 全7テーブルのDDLを作成しました。
-- - マスタテーブル: PUBLISHER, CATEGORY, BOOK, STOCK
-- - トランザクションテーブル: CUSTOMER, ORDER_TRAN, ORDER_DETAIL
-- - 楽観的ロック: STOCKテーブルのVERSIONカラム
-- - 外部キー制約: 全てのリレーションシップに対応
-- - インデックス: 検索最適化のためのインデックスを配置
-- ============================================================================



