-- berry-books-api-sdd Database Schema
-- Database: HSQLDB
-- Purpose: Order management tables only (books/customers managed by other services)

-- Drop existing tables if they exist (in reverse order of dependencies)
DROP TABLE IF EXISTS ORDER_DETAIL;
DROP TABLE IF EXISTS ORDER_TRAN;

-- ============================================================
-- ORDER_TRAN (注文トランザクション)
-- ============================================================
CREATE TABLE ORDER_TRAN (
    ORDER_TRAN_ID   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ORDER_DATE      DATE NOT NULL,
    CUSTOMER_ID     INTEGER NOT NULL,  -- Logical reference only (customer-hub-api manages)
    TOTAL_PRICE     INTEGER NOT NULL,
    DELIVERY_PRICE  INTEGER NOT NULL,
    DELIVERY_ADDRESS VARCHAR(30) NOT NULL,
    SETTLEMENT_TYPE INTEGER NOT NULL   -- 1=Bank, 2=Credit, 3=COD
);

-- Index for customer order history queries
CREATE INDEX IDX_CUSTOMER_ID ON ORDER_TRAN(CUSTOMER_ID);

-- ============================================================
-- ORDER_DETAIL (注文明細)
-- ============================================================
CREATE TABLE ORDER_DETAIL (
    ORDER_TRAN_ID   INTEGER NOT NULL,
    ORDER_DETAIL_ID INTEGER NOT NULL,
    BOOK_ID         INTEGER NOT NULL,     -- Logical reference only (back-office-api manages)
    BOOK_NAME       VARCHAR(100) NOT NULL, -- Snapshot at order time
    PUBLISHER_NAME  VARCHAR(50) NOT NULL,  -- Snapshot at order time
    PRICE           INTEGER NOT NULL,      -- Snapshot at order time
    COUNT           INTEGER NOT NULL,
    PRIMARY KEY (ORDER_TRAN_ID, ORDER_DETAIL_ID),
    FOREIGN KEY (ORDER_TRAN_ID) REFERENCES ORDER_TRAN(ORDER_TRAN_ID) ON DELETE CASCADE
);

-- Index for book reference queries
CREATE INDEX IDX_BOOK_ID ON ORDER_DETAIL(BOOK_ID);

-- ============================================================
-- Schema Information
-- ============================================================
-- Note: BOOK, STOCK, CATEGORY, PUBLISHER tables are managed by back-office-api
-- Note: CUSTOMER table is managed by customer-hub-api
-- This service only manages ORDER_TRAN and ORDER_DETAIL tables
