-- ============================================
-- Books Stock API: テーブル定義
-- ============================================
-- 書籍マスターと在庫テーブルのみ

CREATE TABLE PUBLISHER (
PUBLISHER_ID   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 出版社ID
PUBLISHER_NAME VARCHAR(30) NOT NULL                                   -- 出版社名
);

CREATE TABLE CATEGORY (
CATEGORY_ID   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,   -- カテゴリID
CATEGORY_NAME VARCHAR(20) NOT NULL                                    -- カテゴリ名
);

CREATE TABLE BOOK (
BOOK_ID      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,    -- 書籍ID
BOOK_NAME    VARCHAR(80) NOT NULL,                                    -- 書籍名
AUTHOR       VARCHAR(40) NOT NULL,                                    -- 著者
CATEGORY_ID  INT NOT NULL,                                            -- カテゴリID
PUBLISHER_ID INT NOT NULL,                                            -- 出版社ID
PRICE        INT NOT NULL,                                            -- 価格
IMAGE_URL    VARCHAR(200),                                            -- 画像URL
DELETED      BOOLEAN DEFAULT FALSE NOT NULL,                          -- 論理削除フラグ
CONSTRAINT FK_CATEGORY_ID FOREIGN KEY(CATEGORY_ID)
    REFERENCES CATEGORY(CATEGORY_ID),
CONSTRAINT FK_PUBLISHER_ID FOREIGN KEY(PUBLISHER_ID)
    REFERENCES PUBLISHER(PUBLISHER_ID)
);

CREATE TABLE STOCK (
BOOK_ID      INT    PRIMARY KEY,                                       -- 書籍ID
QUANTITY     INT    NOT NULL,                                          -- 在庫数
VERSION      BIGINT NOT NULL                                           -- バージョン番号
);

CREATE TABLE DEPARTMENT (
DEPARTMENT_ID   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 部署ID
DEPARTMENT_NAME VARCHAR(100) NOT NULL                                 -- 部署名
);

CREATE TABLE EMPLOYEE (
EMPLOYEE_ID     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 社員ID
EMPLOYEE_CODE   VARCHAR(50) NOT NULL UNIQUE,                          -- 社員コード
EMPLOYEE_NAME   VARCHAR(100) NOT NULL,                                -- 社員名
EMAIL           VARCHAR(100),                                         -- メールアドレス
PASSWORD        VARCHAR(100) NOT NULL,                                -- パスワード (BCrypt)
DEPARTMENT_ID   BIGINT NOT NULL,                                      -- 部署ID
JOB_RANK        INTEGER DEFAULT 1 NOT NULL,                           -- 役職ランク (1=ASSOCIATE, 2=MANAGER, 3=DIRECTOR)
CONSTRAINT FK_EMPLOYEE_DEPARTMENT FOREIGN KEY (DEPARTMENT_ID)
    REFERENCES DEPARTMENT (DEPARTMENT_ID)
);

-- ============================================
-- ワークフローテーブル（履歴形式）
-- ============================================
-- 1つのワークフローに対して複数の操作履歴行を持つ
-- WORKFLOW_IDで同じワークフローの操作をグループ化
-- 最新行のSTATEが現在の状態を表す

CREATE TABLE BOOK_WORKFLOW (
-- 主キーと識別子
OPERATION_ID     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 操作ID（主キー）
WORKFLOW_ID      BIGINT NOT NULL,                                     -- ワークフローID（同じワークフローで共通）
WORKFLOW_TYPE    VARCHAR(30) NOT NULL,                                -- ワークフロー種別 (CREATE, DELETE, PRICE_TEMP_ADJUSTMENT)

-- 現在の状態（この操作の結果の状態）
STATE            VARCHAR(20) NOT NULL,                                -- 状態 (NEW, APPLIED, APPROVED)

-- 対象書籍情報（DELETE、PRICE_TEMP_ADJUSTMENTの場合に使用）
BOOK_ID          INT,                                                 -- 対象書籍ID

-- CREATE用の情報
BOOK_NAME        VARCHAR(80),                                         -- 書籍名
AUTHOR           VARCHAR(40),                                         -- 著者
CATEGORY_ID      INT,                                                 -- カテゴリID
PUBLISHER_ID     INT,                                                 -- 出版社ID
IMAGE_URL        VARCHAR(200),                                        -- 画像URL

-- 価格情報（CREATEの場合は新規価格、PRICE_TEMP_ADJUSTMENTの場合は改定後価格）
PRICE            INT,                                                 -- 価格

-- 申請理由（全ワークフロータイプで使用可能）
APPLY_REASON     VARCHAR(500),                                        -- 申請理由（新規追加理由、削除理由、割引理由など）

-- 適用期間（期間限定の申請内容で使用）
START_DATE       DATE,                                                -- 適用開始日
END_DATE         DATE,                                                -- 適用終了日

-- 操作情報（統合）
OPERATION_TYPE   VARCHAR(20) NOT NULL,                                -- 操作タイプ (CREATE, APPLY, APPROVE, REJECT)
OPERATED_BY      BIGINT NOT NULL,                                     -- 操作者ID
OPERATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,        -- 操作日時
OPERATION_REASON VARCHAR(500),                                        -- 操作理由（主にREJECTの場合）

-- 外部キー制約
CONSTRAINT FK_WORKFLOW_BOOK FOREIGN KEY (BOOK_ID)
    REFERENCES BOOK (BOOK_ID),
CONSTRAINT FK_WORKFLOW_CATEGORY FOREIGN KEY (CATEGORY_ID)
    REFERENCES CATEGORY (CATEGORY_ID),
CONSTRAINT FK_WORKFLOW_PUBLISHER FOREIGN KEY (PUBLISHER_ID)
    REFERENCES PUBLISHER (PUBLISHER_ID),
CONSTRAINT FK_WORKFLOW_OPERATED_BY FOREIGN KEY (OPERATED_BY)
    REFERENCES EMPLOYEE (EMPLOYEE_ID)
);