openapi: 3.0.3
info:
  title: Books Stock API - ワークフローAPI
  description: |
    バックオフィス書籍在庫管理システムのワークフローAPI仕様
    
    書籍マスタ変更のワークフロー管理（申請・承認フロー）機能を提供する。
    
    ## ワークフロー状態遷移
    
    * CREATED（作成済み） → APPLIED（申請中） → APPROVED（承認済み）
    * APPLIED（申請中） → CREATED（作成済み）※却下時
    
    ## ワークフロータイプ
    
    * ADD_NEW_BOOK: 新規書籍追加
    * REMOVE_BOOK: 既存書籍削除
    * ADJUST_BOOK_PRICE: 書籍価格改定
  version: 1.0.0
  contact:
    name: API Support
    email: support@example.com

servers:
  - url: http://localhost:8080/api
    description: 開発環境
  - url: https://api.example.com/api
    description: 本番環境

tags:
  - name: workflows
    description: ワークフロー操作

paths:
  /workflows:
    post:
      tags:
        - workflows
      summary: ワークフロー作成
      description: 新しいワークフローを作成する（新規書籍追加、既存書籍削除、価格改定）
      operationId: createWorkflow
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/AddNewBookRequest'
                - $ref: '#/components/schemas/RemoveBookRequest'
                - $ref: '#/components/schemas/AdjustBookPriceRequest'
              discriminator:
                propertyName: workflowType
                mapping:
                  ADD_NEW_BOOK: '#/components/schemas/AddNewBookRequest'
                  REMOVE_BOOK: '#/components/schemas/RemoveBookRequest'
                  ADJUST_BOOK_PRICE: '#/components/schemas/AdjustBookPriceRequest'
      responses:
        '201':
          description: ワークフロー作成成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowResponse'
        '400':
          description: リクエストが不正
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: サーバー内部エラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    get:
      tags:
        - workflows
      summary: ワークフロー一覧取得
      description: ワークフロー一覧を取得する（フィルタリング可能）
      operationId: getWorkflows
      parameters:
        - name: state
          in: query
          description: ワークフロー状態でフィルタ
          required: false
          schema:
            type: string
            enum: [CREATED, APPLIED, APPROVED]
        - name: workflowType
          in: query
          description: ワークフロータイプでフィルタ
          required: false
          schema:
            type: string
            enum: [ADD_NEW_BOOK, REMOVE_BOOK, ADJUST_BOOK_PRICE]
        - name: employeeId
          in: query
          description: 社員IDでフィルタ
          required: false
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: ワークフロー一覧取得成功
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WorkflowResponse'
        '500':
          description: サーバー内部エラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /workflows/{workflowId}:
    put:
      tags:
        - workflows
      summary: ワークフロー更新（一時保存）
      description: 作成済みワークフローの内容を更新する（CREATED状態のみ）
      operationId: updateWorkflow
      parameters:
        - name: workflowId
          in: path
          required: true
          description: ワークフローID
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WorkflowUpdateRequest'
      responses:
        '200':
          description: ワークフロー更新成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowResponse'
        '404':
          description: ワークフローが見つかりません
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: サーバー内部エラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /workflows/{workflowId}/history:
    get:
      tags:
        - workflows
      summary: ワークフロー履歴取得
      description: 指定されたワークフローの操作履歴を取得する
      operationId: getWorkflowHistory
      parameters:
        - name: workflowId
          in: path
          required: true
          description: ワークフローID
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: ワークフロー履歴取得成功
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WorkflowResponse'
        '404':
          description: ワークフローが見つかりません
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: サーバー内部エラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /workflows/{workflowId}/apply:
    post:
      tags:
        - workflows
      summary: ワークフロー申請
      description: 作成済みワークフローを申請する（CREATED → APPLIED）
      operationId: applyWorkflow
      parameters:
        - name: workflowId
          in: path
          required: true
          description: ワークフローID
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WorkflowOperationRequest'
      responses:
        '200':
          description: ワークフロー申請成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowResponse'
        '404':
          description: ワークフローが見つかりません
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: サーバー内部エラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /workflows/{workflowId}/approve:
    post:
      tags:
        - workflows
      summary: ワークフロー承認
      description: |
        申請中ワークフローを承認する（APPLIED → APPROVED）
        
        承認権限:
        * MANAGER（職務ランク2）: 同一部署のみ承認可
        * DIRECTOR（職務ランク3）: 全部署承認可
        * ASSOCIATE（職務ランク1）: 承認不可
      operationId: approveWorkflow
      parameters:
        - name: workflowId
          in: path
          required: true
          description: ワークフローID
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WorkflowOperationRequest'
      responses:
        '200':
          description: ワークフロー承認成功（書籍マスタへ反映済み）
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowResponse'
        '403':
          description: 承認権限がありません
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: ワークフローが見つかりません
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: サーバー内部エラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /workflows/{workflowId}/reject:
    post:
      tags:
        - workflows
      summary: ワークフロー却下
      description: 申請中ワークフローを却下する（APPLIED → CREATED）
      operationId: rejectWorkflow
      parameters:
        - name: workflowId
          in: path
          required: true
          description: ワークフローID
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WorkflowOperationRequest'
      responses:
        '200':
          description: ワークフロー却下成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowResponse'
        '404':
          description: ワークフローが見つかりません
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: サーバー内部エラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    AddNewBookRequest:
      type: object
      required:
        - workflowType
        - createdBy
        - bookName
        - author
        - price
        - categoryId
        - publisherId
        - applyReason
      properties:
        workflowType:
          type: string
          enum: [ADD_NEW_BOOK]
          description: ワークフロータイプ
        createdBy:
          type: integer
          format: int64
          description: 作成者の社員ID
        bookName:
          type: string
          description: 書籍名
        author:
          type: string
          description: 著者名
        price:
          type: number
          format: double
          description: 価格（円）
          minimum: 0
        imageUrl:
          type: string
          format: uri
          description: 画像URL
        categoryId:
          type: integer
          format: int32
          description: カテゴリID
        publisherId:
          type: integer
          format: int32
          description: 出版社ID
        applyReason:
          type: string
          description: 申請理由

    RemoveBookRequest:
      type: object
      required:
        - workflowType
        - createdBy
        - bookId
        - applyReason
      properties:
        workflowType:
          type: string
          enum: [REMOVE_BOOK]
          description: ワークフロータイプ
        createdBy:
          type: integer
          format: int64
          description: 作成者の社員ID
        bookId:
          type: integer
          format: int32
          description: 削除対象の書籍ID
        applyReason:
          type: string
          description: 申請理由

    AdjustBookPriceRequest:
      type: object
      required:
        - workflowType
        - createdBy
        - bookId
        - price
        - startDate
        - endDate
        - applyReason
      properties:
        workflowType:
          type: string
          enum: [ADJUST_BOOK_PRICE]
          description: ワークフロータイプ
        createdBy:
          type: integer
          format: int64
          description: 作成者の社員ID
        bookId:
          type: integer
          format: int32
          description: 価格改定対象の書籍ID
        price:
          type: number
          format: double
          description: 新しい価格（円）
          minimum: 0
        startDate:
          type: string
          format: date
          description: 適用開始日（ISO 8601形式）
        endDate:
          type: string
          format: date
          description: 適用終了日（ISO 8601形式）
        applyReason:
          type: string
          description: 申請理由

    WorkflowUpdateRequest:
      type: object
      required:
        - updatedBy
      properties:
        updatedBy:
          type: integer
          format: int64
          description: 更新者の社員ID
        bookName:
          type: string
          description: 書籍名（ADD_NEW_BOOKの場合）
        author:
          type: string
          description: 著者名（ADD_NEW_BOOKの場合）
        price:
          type: number
          format: double
          description: 価格（円）
        imageUrl:
          type: string
          format: uri
          description: 画像URL
        categoryId:
          type: integer
          format: int32
          description: カテゴリID
        publisherId:
          type: integer
          format: int32
          description: 出版社ID
        startDate:
          type: string
          format: date
          description: 適用開始日
        endDate:
          type: string
          format: date
          description: 適用終了日
        applyReason:
          type: string
          description: 申請理由

    WorkflowOperationRequest:
      type: object
      required:
        - operatedBy
      properties:
        operatedBy:
          type: integer
          format: int64
          description: 操作者の社員ID
        operationReason:
          type: string
          description: 操作理由

    WorkflowResponse:
      type: object
      properties:
        operationId:
          type: integer
          format: int64
          description: 操作ID
        workflowId:
          type: integer
          format: int64
          description: ワークフローID
        workflowType:
          type: string
          enum: [ADD_NEW_BOOK, REMOVE_BOOK, ADJUST_BOOK_PRICE]
          description: ワークフロータイプ
        state:
          type: string
          enum: [CREATED, APPLIED, APPROVED]
          description: ワークフロー状態
        bookId:
          type: integer
          format: int32
          description: 書籍ID（REMOVE_BOOK、ADJUST_BOOK_PRICEの場合）
        bookName:
          type: string
          description: 書籍名
        author:
          type: string
          description: 著者名
        price:
          type: number
          format: double
          description: 価格（円）
        imageUrl:
          type: string
          format: uri
          description: 画像URL
        categoryId:
          type: integer
          format: int32
          description: カテゴリID
        categoryName:
          type: string
          description: カテゴリ名
        publisherId:
          type: integer
          format: int32
          description: 出版社ID
        publisherName:
          type: string
          description: 出版社名
        startDate:
          type: string
          format: date
          description: 適用開始日
        endDate:
          type: string
          format: date
          description: 適用終了日
        applyReason:
          type: string
          description: 申請理由
        operationType:
          type: string
          enum: [CREATE, APPLY, APPROVE, REJECT]
          description: 操作タイプ
        operatedBy:
          type: integer
          format: int64
          description: 操作者の社員ID
        operatorName:
          type: string
          description: 操作者名
        operatorCode:
          type: string
          description: 操作者の社員コード
        jobRank:
          type: integer
          description: 操作者の職務ランク
        departmentId:
          type: integer
          format: int64
          description: 操作者の部署ID
        departmentName:
          type: string
          description: 操作者の部署名
        operatedAt:
          type: string
          format: date-time
          description: 操作日時（ISO 8601形式）

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: エラータイプ
        message:
          type: string
          description: エラーメッセージ（日本語）
